name: example
description: Example project for relogio_package
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_wear_os_connectivity:
    git:
      url: https://github.com/maks-epowar/flutter_wear_os_connectivity.git 
      ref: master

  # Ícones opcionais para iOS (não afetam Wear OS)
  cupertino_icons: ^1.0.8

  # Dependência para usar o package local
  relogio_package:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
